# Generated by Django 2.2 on 2019-04-24 06:36

from django.db import migrations, models
import news.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(max_length=255)),
                ('created_at', models.DateField()),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(max_length=10000)),
                ('priority', models.IntegerField(default=news.models.get_next)),
            ],
        ),
    ]
