# Generated by Django 2.2 on 2019-04-24 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendances',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=255)),
                ('mtg_id', models.CharField(max_length=255)),
                ('ip_address', models.CharField(max_length=255)),
                ('attend', models.BooleanField()),
                ('description', models.TextField(default='No Description', max_length=500)),
                ('is_presentationed', models.BooleanField(default=False)),
            ],
        ),
    ]
