# Generated by Django 2.2 on 2019-04-24 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendances',
            name='bw_id',
            field=models.CharField(default='NONE', max_length=255),
        ),
    ]
