# Generated by Django 2.2.5 on 2019-09-24 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_attendances_bw_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendances',
            name='attend',
            field=models.BooleanField(default=True),
        ),
    ]
