# Generated by Django 2.2.1 on 2019-05-09 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_name', models.CharField(max_length=255)),
                ('full_japanese_name', models.CharField(max_length=255)),
                ('full_english_name', models.CharField(max_length=255)),
                ('grade', models.CharField(max_length=255)),
                ('faculity', models.CharField(max_length=255)),
            ],
        ),
    ]
