# Generated by Django 2.2.1 on 2019-05-12 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='browser_id',
            field=models.CharField(default='NONE', max_length=255),
        ),
    ]
