# Generated by Django 2.2.1 on 2019-05-14 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0002_member_browser_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='browser_id',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
