# Generated by Django 2.2.1 on 2019-05-14 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('text', models.TextField()),
                ('content_type', models.CharField(max_length=30)),
                ('created_by', models.CharField(max_length=50)),
                ('is_deleted', models.BooleanField()),
                ('is_updated', models.BooleanField()),
            ],
        ),
    ]
