# Generated by Django 2.2.1 on 2019-05-15 03:34

from django.db import migrations, models
import field.models


class Migration(migrations.Migration):

    dependencies = [
        ('field', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='is_highlight',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='content',
            name='is_warning',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='content',
            name='priority',
            field=models.IntegerField(default=field.models.get_next),
        ),
    ]
