# Generated by Django 2.2.1 on 2019-05-15 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field', '0002_auto_20190515_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='content',
            name='is_updated',
            field=models.BooleanField(default=False),
        ),
    ]
