# Generated by Django 3.2 on 2021-04-12 12:30

from django.db import migrations, models
import django.utils.timezone
import manager.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendances',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mtg_id', models.CharField(max_length=255)),
                ('login_name', models.CharField(max_length=255)),
                ('attend', models.BooleanField()),
                ('mtg_ref', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Meetings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mtg_id', models.CharField(max_length=255)),
                ('time', models.IntegerField(default=manager.models.get_next)),
                ('active', models.BooleanField(default=True)),
                ('period', models.IntegerField(default=6)),
                ('due_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_online', models.BooleanField(default=True)),
                ('campus', models.CharField(default='', max_length=255)),
                ('room', models.CharField(default='', max_length=255)),
                ('gas_url', models.CharField(default='', max_length=255)),
                ('qasys', models.CharField(default='', max_length=255)),
                ('elementaly_presenters', models.CharField(default='', max_length=500)),
                ('secondary_presenters', models.CharField(default='', max_length=500)),
                ('description', models.CharField(default='', max_length=1000)),
                ('zoom_url', models.CharField(default='', max_length=255)),
                ('webex_url', models.CharField(default='', max_length=255)),
            ],
        ),
    ]
