# Generated by Django 3.2 on 2021-05-19 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetings',
            name='title',
            field=models.CharField(default='None title', max_length=255),
        ),
    ]
