# Generated by Django 2.2.5 on 2019-09-23 13:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_meetings_gas_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetings',
            name='campus',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='meetings',
            name='elementaly_presenters',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='meetings',
            name='period',
            field=models.IntegerField(default=6),
        ),
        migrations.AddField(
            model_name='meetings',
            name='regist_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='meetings',
            name='room',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='meetings',
            name='secondary_presenters',
            field=models.CharField(default='', max_length=500),
        ),
    ]
