# Generated by Django 2.2.5 on 2019-09-23 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0004_auto_20190923_2216'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetings',
            name='description',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
