# Generated by Django 2.2.5 on 2019-09-25 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0006_auto_20190923_2233'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetings',
            name='qasys',
            field=models.CharField(default='', max_length=255),
        ),
    ]
